#!/usr/bin/env bash
# shellcheck disable=SC2034
#
# Reports *.sh shellcheck issues in folder and all subfolders
# Author: Igor P. Zenkov
# Dependency: https://www.shellcheck.net CLI
#

declare -r SCRIPT_NAME="${0##*/}"
declare -r SCRIPT_VERSION='1.0.3 Jan 15, 2022'
declare -r FGLOB='*.sh'

function bold { printf '\e[96m%s\e[0m\n' "$*"; }
function err  { >&2 printf "%s: \e[91m%s\e[0m\n" "$SCRIPT_NAME" "$*"; }
function halt { err "$@"; exit 3; }

function assert_bash {
  local -r maj_exp=$1 # expected
  local -r maj_act="${BASH_VERSION:0:1}" # actual
  ((maj_act>=maj_exp)) || halt "Bash $BASH_VERSION detected, please upgrade to version $maj_exp or newer"
}

function assert_shellcheck {
  shellcheck --help > /dev/null 2>&1 || halt 'shellcheck (www.shellcheck.net) not found'
}

function assert_dir {
  [[ -d $1 ]] || halt "folder '$1' not found"
}

function assert_cd {
  cd "$1" || halt "unable to chage folder to '$1'"
}

function set_parent_dir {
  local -n r_var=$1
  local -r dir=$PWD
  assert_dir "$2";
  assert_cd  "$2"
  case $PWD in
    '/') r_var='/';;
      *) r_var=${PWD##*/};;
  esac
  assert_cd "$dir"
}

function check_file {
  shellcheck -x -f gcc "$1" | wc -l
}

# report all
function report_a {
  local -r dir=$1 pdir=$2
  local -a scripts
  readarray -t scripts < <(find "$dir" -name "$FGLOB")
  local scr; local -i cnt total=0
  bold "$SCRIPT_NAME $SCRIPT_VERSION"
  echo
  echo "$pdir"
  echo
  for scr in "${scripts[@]}"; do
    [[ -f $scr ]] || continue
    cnt=$(check_file "$scr")
    printf '%3d %s\n' "$cnt" "$scr"
    ((total+=cnt))
  done
  echo
  echo "$total issues in ${#scripts[@]} $FGLOB files"
}

# report all excluding scripts with 0 errors
function report_0 {
  local -r dir=$1 pdir=$2
  local -a scripts
  readarray -t scripts < <(find "$dir" -name "$FGLOB")
  local scr; local -i cnt total=0 errcnt=0
  bold "$SCRIPT_NAME $SCRIPT_VERSION"
  echo
  echo "$pdir"
  echo
  for scr in "${scripts[@]}"; do
    [[ -f $scr ]] || continue
    cnt=$(check_file "$scr")
    if ((cnt!=0)); then
      printf '%3d %s\n' "$cnt" "$scr"
      ((errcnt++))
    fi
    ((total+=cnt))
  done
  echo
  echo "$total issues in $errcnt $FGLOB files"
}

# report total error count
function report_c {
  local -r dir=$1 pdir=$2
  local -a scripts
  readarray -t scripts < <(find "$dir" -name "$FGLOB")
  local scr; local -i cnt total=0
  for scr in "${scripts[@]}"; do
    [[ -f $scr ]] || continue
    cnt=$(check_file "$scr")
    ((total+=cnt))
  done
  echo "$total"
}

# quiet mode, return exit code
function report_q {
  local -r dir=$1 pdir=$2
  local -a scripts
  readarray -t scripts < <(find "$dir" -name "$FGLOB")
  local scr; local -i cnt total=0
  for scr in "${scripts[@]}"; do
    [[ -f $scr ]] || continue
    cnt=$(check_file "$scr")
    ((total+=cnt))
  done
  ((total==0)) || exit 1
}

function report {
  assert_shellcheck
  local -r dir=$1
  local -r opt=$2 # -0, -c, or -q
  local pdir
  set_parent_dir pdir "$dir"
  case $opt in
    -0) report_0 "$dir" "$pdir";;
    -c) report_c "$dir" "$pdir";;
    -q) report_q "$dir" "$pdir";;
     *) report_a "$dir" "$pdir";;
  esac
}

function usage {
  bold "$SCRIPT_NAME $SCRIPT_VERSION"
  echo
  echo " Usage: $SCRIPT_NAME <dir>"
  echo "        $SCRIPT_NAME -0 <dir>"
  echo "        $SCRIPT_NAME -c <dir>"
  echo "        $SCRIPT_NAME -q <dir>"
  echo "        $SCRIPT_NAME -v"
  echo "        $SCRIPT_NAME -h"
  echo
  echo ' Where: <dir>  Folder to scan'
  echo '        -0     Exclude 0 errors scripts'
  echo '        -c     Print error count'
  echo '        -q     Quiet, return exit code'
  echo '        -v     Version'
  echo '        -h     Help'
  echo
  (($#==0)) && return
  echo " Like:  $SCRIPT_NAME ."
  echo "        $SCRIPT_NAME -0 ."
  echo "        $SCRIPT_NAME -c ."
  echo "        $SCRIPT_NAME -q ."
  echo "        $SCRIPT_NAME ./git"
  echo "        $SCRIPT_NAME ~/dev"
  echo
  echo ' Exit codes (-q option)'
  echo
  echo '  0: Folder scan completed, no issues found'
  echo '  1: Folder scan completed, issues found'
  echo '  3: Bad syntax or options'
  echo
}

function one_arg {
  case $1 in
    -0|-c|-q) halt 'missing <dir> argument';;
    -h) usage '-h';;
    -v) echo "$SCRIPT_VERSION";;
    -*) halt "unknown argument '$1'";;
     *) report "$1";;
  esac
}

function two_arg {
  case $1 in
    -0|-c|-q) report "$2" "$1";; # reverse arguments: <dir> <opt>
    *) halt "unknown argument '$1'";;
  esac
}

function main {
  assert_bash 4
  case $# in
    0) usage;;
    1) one_arg "$@";;
    2) two_arg "$@";;
    *) halt 'too many arguments';;
  esac
}

main "$@"
