#!/bin/sh

BIN_FILE='shellcheck-report'
BIN_PATH="/usr/local/bin/${BIN_FILE}"
RUN_VERBOSE='N'

err() {
  >&2 echo "$*"
}

msg() {
  [ "$RUN_VERBOSE" = 'N' ] || echo "$@"
}

exit_failure() {
  [ $# -ne 0 ] && err "$@"
  exit 1
}

exit_success() {
  [ $# -ne 0 ] && echo "$@"
  exit 0;
}

assert_uninstalled() {
  if [ ! -f "$BIN_PATH" ]; then
    msg "'${BIN_PATH}' file not found"
    exit_success "'${BIN_FILE}' already uninstalled"
  fi
}

usage() {
  if [ -f "${BIN_PATH}" ]; then
    echo "${BIN_FILE} $(${BIN_PATH} -v) uninstaller"
  else
    echo "${BIN_FILE} uninstaller"
  fi
  echo 'Usage: uninstall'
  echo '       uninstall -v (verbose)'
  echo '       uninstall -h'
}

main () {
  if [ $# -ne 0 ]; then
    case $1 in
      -v) RUN_VERBOSE='Y';;
      -h) { usage; return; };;
       *) exit_failure "Unknown option: '$1'"
    esac
  fi

  assert_uninstalled

  msg "Uninstalling '${BIN_FILE}' ..."
  msg "Removing '${BIN_PATH}' file ..."
  sudo rm "${BIN_PATH}"

  [ -f "$BIN_PATH" ] && exit_failure ''${BIN_FILE}' uninstall failure'
}

main "$@"

